module.exports = {
  'page1': {
    'links': {
      'next': '/v2/service-provider-needs?latitude=53.4873656112133&longitude=-2.22721197039864&index=21&pageSize=21',
      'prev': null,
      'self': '/v2/service-provider-needs?latitude=53.4873656112133&longitude=-2.22721197039864&index=0&pageSize=21'
    },
    'items': [
      {
        'id': '57e3f90fcbad0f1e28bf3d78',
        'description': 'Customer Services Assistant &ndash; Ancoats, Eccles or Little Hulton',
        'type': 'time',
        'reason': 'We currently operate 3 shops in Ancoats, Eccles &amp; Little Hulton and offer a wide range of furniture, clothes and household goods. Some of the stock is new but the big majority is pre-loved at prices we believe are hard to match anywhere in Greater Manchester. Our shops operate as far more than just retail spaces being the entry point for people seeking support from one of the other services that Mustard Tree offers. They are the front door to our community, and we aim to treat everyone looking for support with dignity and care. The shops are looked after by our greatly valued volunteers, many of which have firstly come to as clients and who are enrolled on one of our life skills and employment programmes.&#10;&#10;We are looking for people who are able to support our Retail team in the day to day running of our charity shop. Main activities include:&#10;&#10;Act a buddy to Freedom Project participants to develop new skills and achieve their personal development goals (only in Ancoats and Little Hulton)&#10;&#10;Welcome and advise customers and clients&#10;Sort donations of clothing and homeware&#10;Ensure goods are well displayed&#10;Assist with regular stock checks&#10;Operate the till and accurately handle payments&#10;Answer the telephones&#10;Book collections and deliveries in&#10;Be vigilant at all times and to help minimise stock loss&#10;Process food parcels&#10;&#10;Time commitment: We are looking for volunteers who are able to commit to a day (or more) per week. This could be split across two morning or afternoon sessions. A normal working day is from 09: 00 &ndash; 17: 00.&#10;&#10;Expenses: We are able to refund volunteers for travel expenses and provide lunch.&#10;&#10;Please apply by downloading an application form from our website and emailing to us. ',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/how-to-apply/',
        'postcode': 'M4 6AG',
        'instructions': null,
        'email': 'volunteering@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-22T15:30:23.7460000Z',
        'neededDate': '2016-09-22T15:30:23.7460000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'volunteering',
          'retail',
          'customer services'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '57e3fa6acbad0f1e28bf3de7',
        'description': 'Music Production Tutor &ndash; Ancoats',
        'type': 'time',
        'reason': 'The James Hardy Music Studio aims to teach clients the skills needed to make their own music, by providing all the equipment and information they need. We hope that the process of making music will have a positive influence, helping clients become part of a community and family.&#10;&#10;Main activities for the role include the following:&#10;&#10;Fully trained in using Digital Audio Workstation; Reaper&#10;Able to plan, teach and lead a 10-week music production course using&#10;Have a passion for music and passing on your knowledge and skills to others&#10;Time commitment: The weekly course will take place on Monday&rsquo;s, 18: 00 &ndash; 20: 00 so we are looking for someone who can commit to this time.&#10;&#10;Disclosure and Barring Service Check: A Disclosure and Barring Service Check (formerly CRB check) will be required as part of this role. This is free of charge for applicants.&#10;&#10;Expenses: We are able to refund volunteers for travel expenses&#10;&#10;Please apply by downloading an application form from our website and emailing to us.',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/how-to-apply/',
        'postcode': 'M4 6AG',
        'instructions': null,
        'email': 'volunteering@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-22T15:36:10.9000000Z',
        'neededDate': '2016-09-22T15:36:10.9000000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Volunteering',
          'music'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '58239c62ddad5b11dcdd8840',
        'description': 'Male toiletries e.g. shower gel, shampoo/conditioner, razors, shaving gel, deodorant',
        'type': 'items',
        'reason': 'We are desperately low on items for rough sleepers, especially men, and we receive regular requests for these items',
        'moreInfoUrl': null,
        'postcode': 'M4 6AG',
        'instructions': 'Please drop items at our Ancoats hub: 110 Oldham Road, M4 6AG&#10;or contact us',
        'email': 'info@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-11-09T22:00:02.7270000Z',
        'neededDate': '2016-11-09T22:00:02.7270000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Shower gel',
          'shampoo',
          'conditioner',
          'razors',
          'shaving gel',
          'deodorant'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '58239b9fddad5b11dcdd87f7',
        'description': 'Sleeping bags / Woolly hats / Gloves ',
        'type': 'items',
        'reason': 'We are desperately low on items to give to rough sleepers and we are regularly being asked for these ',
        'moreInfoUrl': null,
        'postcode': 'M4 6AG',
        'instructions': 'Please drop off items at our Ancoats hub: 110 Oldham Road, Ancoats, M4 6AG or contact us',
        'email': 'info@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-11-09T21:56:47.0880000Z',
        'neededDate': '2016-11-09T21:56:47.0880000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Sleeping Bags',
          'Wooly Hats',
          'Gloves'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '57e3fa26cbad0f1e28bf3dc2',
        'description': 'Food Club Assistant &ndash; Ancoats',
        'type': 'time',
        'reason': 'We are moving our service users away from the Food Bank model towards our Food Club, which provides a food basket of 10 items for a membership fee of &pound;2 per week, by redistributing surplus food stocks through Fareshare.&#10;&#10;Your main task as a Food Club Assistant is to ensure that our clients have an enjoyable and educational experience when accessing our Food Club project. As part of this role, you will be expected to:&#10;&#10;Buddy up with Freedom Project participants to develop new skills and achieve their personal development goals&#10;Welcome and assist clients in choosing food from the Food Club&#10;Enable clients to make healthier choices about the food they eat through the use of advice, recipe cards and demonstrations&#10;Ensure goods are well displayed and inviting, following merchandising guidelines&#10;Assist with regular stock checks, date checks and temperature checks&#10;Be vigilant at all times and to help minimise stock loss&#10;Time commitment: We are looking for volunteers who are able to commit to a day (or more) per week. This could be split across two morning or afternoon sessions. A normal working day is from 09: 00 &ndash; 17: 00.&#10;&#10;Expenses: We are able to refund volunteers for travel expenses and provide lunch.&#10;&#10;Please apply by downloading an application form from our website and emailing to us.',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/how-to-apply/',
        'postcode': 'M4 6AG',
        'instructions': null,
        'email': 'volunteering@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-22T15:35:02.7000000Z',
        'neededDate': '2016-09-22T15:35:02.7000000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Volunteering',
          'food',
          ''
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '57eb711fcbad0f1a6092eb2a',
        'description': 'Picture frames',
        'type': 'items',
        'reason': 'In collaboration with the New Islington Free School, we worked on an art installation called &#39;The Trees of Ancoats&#39;  with the intention of brightening up the surrounding area of the school&#39;s new building. Our Creative Programmes Manager Graham initially came up with the idea of fusing nature and city life together and with the support of the pupils, teachers and our Freedom Project participants, pictures of trees were drawn in class and at Mustard Tree which were transferred onto large wooden boards. In addition to this, Graham talked to pupils about the importance of the environment, what trees do and why they are vital to every living creature on the planet. In total, 34 trees have been placed on the fences of the New Islington Free School which we hope will give Ancoats a fresh identity and encourage community spirit. &#10;&#10;We would like to frame the original art work produced by the the children and present each one to the children after exhibiting them both at Mustard Tree and at the school. We are looking for 69 A4 and 6 A3 size frames for the project so if this is something you can help with, please do get in touch!',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/2016/09/trees-of-ancoats/',
        'postcode': 'M4 6AG',
        'instructions': '',
        'email': 'info@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-28T07:28:31.7910000Z',
        'neededDate': '2016-09-28T07:28:31.7910000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'picture frames',
          'art',
          'community'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '57e3fae4cbad0f1e28bf3e31',
        'description': 'Skills Mentor &ndash; Ancoats',
        'type': 'time',
        'reason': 'Every Tuesday from 10am-12pm, we provide a place for people who have additional barriers to moving on in life, such as homelessness, mental health issues, addiction recovery or a criminal record, get support in finding work.&#10;&#10;People come to get help with lots of things.  It could be making their first CV in years, using the computer, preparing for a daunting interview or just getting a bit of encouragement.  Crucial to offering this support are our skills mentors, people from the community who give attendees a little focused time that goes a long way.&#10;&#10;We are looking for more skills mentors to join our team.  If you can volunteer at least one Tuesday a month, are confident in using computers, good at talking to different people and want to support someone towards getting the job that could really change their lives, we would love to hear from you.&#10;&#10;Time Commitment: We ask volunteers to commit a minimum of around one session a month which is based around our &ldquo;Ready for Work&rdquo; club. At our Ancoats Hub this is every Tuesday 10am-12pm.  We are still developing Ready for Work club at our Little Hulton base so a time and date is still to be confirmed.&#10;&#10;Please get in touch if you&#39;re interested in volunteering in this role with us. ',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/how-to-apply/',
        'postcode': 'M4 6AG',
        'instructions': '',
        'email': 'volunteering@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-22T15:38:12.9950000Z',
        'neededDate': '2016-09-22T15:38:12.9950000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Volunteering',
          'skills',
          'mentor',
          'training'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '58d38afab421f80a84d887cb',
        'description': 'Rebuild Move Volunteers ',
        'type': 'time',
        'reason': 'Against a backdrop of national austerity, public service cuts and spiralling deprivation, Mustard Tree  is innovating, re-building, and upgrading to tackle poverty, inequality and disadvantage across our city. While our Ancoats building is structurally sound, it was never designed for the work we do. Without major refurbishments it would become soon become impossible to maintain our existing services, let alone meet the rising need we face on a day-to-day basis.  &#10;&#10;We are undertaking major refurbishments at our hub in Ancoats and are looking for volunteers to help us move our training and catering facilities to a nearby building and create space for the refurbishments to begin. &#10;',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/2017/03/help-us-to-rebuild-our-ancoats-hub/',
        'postcode': 'M4 6AG',
        'instructions': 'Please complete the application form on our website and email to volunteering@mustardtree.co.uk, along with your availability. ',
        'email': 'volunteering@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-03-23T08:44:42.4410000Z',
        'neededDate': '2017-03-23T08:44:42.4410000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'lifting',
          'manual',
          'time'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '58a5a20f0bc3da271c6a96e1',
        'description': 'Essential Food Store Items',
        'type': 'items',
        'reason': 'High demand on services.',
        'moreInfoUrl': 'http: //www.mustardtree.org.uk/wp-content/uploads/2009/10/Food-Essential-Items.pdf',
        'postcode': 'M4 6AG',
        'instructions': 'As well as food store items we also require clothing and furniture. For further info and to donate, please visit http: //www.mustardtree.org.uk or call 0161 228 7331',
        'email': 'info@mustardtree.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-02-16T12:58:55.3430000Z',
        'neededDate': '2017-02-16T12:58:55.3430000Z',
        'serviceProviderId': 'mustard-tree',
        'serviceProviderName': 'Mustard Tree',
        'serviceProviderSynopsis': 'Mustard Tree provide practical support, friendship, connections into work, improvements to wellbeing and new experiences to encourage aspiration',
        'keywords': [
          'Dried Food',
          'Jars &amp; Tins',
          'Packets &amp; Cartons',
          'Personal Items'
        ],
        'longitude': -2.22764482381055,
        'latitude': 53.4865827925854,
        'customMessage': null
      },
      {
        'id': '57750792474f8b125854f352',
        'description': 'Men&#39;s bike',
        'type': 'items',
        'reason': 'One of our clients has had his bike stolen - it&#39;s really important to him as it enables him to get around. If anyone has one spare it would be wonderful. ',
        'moreInfoUrl': null,
        'postcode': 'M4 6AG',
        'instructions': 'Please get in touch on twitter @boaztrust or by email if you can help.',
        'email': 'info@boaztrust.org.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-06-30T11:50:42.3000000Z',
        'neededDate': '2016-06-30T11:50:42.3000000Z',
        'serviceProviderId': 'boaz-trust',
        'serviceProviderName': 'Boaz Trust',
        'serviceProviderSynopsis': 'Ending asylum destitution in the UK',
        'keywords': [
          'Bike'
        ],
        'longitude': -2.2277651447334,
        'latitude': 53.4865376210618,
        'customMessage': null
      },
      {
        'id': '571003a20dad0a129803f44a',
        'description': 'Lentils, tea bags and tinned tomatoes.',
        'type': 'items',
        'reason': 'We often need food items and teabags to provide warm meals and drinks for the people we support.',
        'moreInfoUrl': 'http: //boaztrust.org.uk/get-involved/support/',
        'postcode': 'M4 6AG',
        'instructions': 'Drop off at our centre Mon-Fri 10am-4pm, or email info@boaztrust.org.uk.',
        'email': 'info@boaztrust.org.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-04-14T20:54:58.9360000Z',
        'neededDate': '2016-04-14T20:54:58.9360000Z',
        'serviceProviderId': 'boaz-trust',
        'serviceProviderName': 'Boaz Trust',
        'serviceProviderSynopsis': 'Ending asylum destitution in the UK',
        'keywords': [
          'Food',
          'Teabags'
        ],
        'longitude': -2.2277651447334,
        'latitude': 53.4865376210618,
        'customMessage': null
      },
      {
        'id': '571004190dad0a129803f44b',
        'description': 'Fresh food for 5 people for a week',
        'type': 'money',
        'reason': 'Please stand with us and help us bring hope to more asylum seekers and refugees. A gift of £25 will buy bedding for a destitute asylum seeker moving from street homelessness into the safety of one of our houses. A gift of &pound;50 will pay for five asylum seekers to have fresh food for one week. A gift of £250 will buy fresh fruit, vegetables and basic toiletries for up to 30 asylum seekers who attend our monthly drop in.',
        'moreInfoUrl': 'http: //boaztrust.org.uk/get-involved/',
        'postcode': 'M4 6AG',
        'instructions': null,
        'email': null,
        'donationAmountInPounds': 50,
        'donationUrl': 'https: //www.give.net/20100645',
        'creationDate': '2016-04-14T20:56:57.7570000Z',
        'neededDate': '2016-04-14T20:56:57.7570000Z',
        'serviceProviderId': 'boaz-trust',
        'serviceProviderName': 'Boaz Trust',
        'serviceProviderSynopsis': 'Ending asylum destitution in the UK',
        'keywords': [
          'Money',
          'Food'
        ],
        'longitude': -2.2277651447334,
        'latitude': 53.4865376210618,
        'customMessage': null
      },
      {
        'id': '56d9b9c9a3b948fda0b49373',
        'description': 'Money mentoring and financial literacy support',
        'type': 'time',
        'reason': 'Many of our clients find it hard to manage their money. Advice and basic training on how to do this could make a real difference to them being able to stay in their accommodation and off of the streets.',
        'moreInfoUrl': 'http: //www.lifeshare.org.uk/volunteer/breakfast',
        'postcode': 'M1 1EB',
        'instructions': 'We can arrange the sessions and location, please get in touch if you could help.',
        'email': 'viv@streetsupport.net',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-03-04T16:37:29.0740000Z',
        'neededDate': '2018-06-13T14:50:25.5710000Z',
        'serviceProviderId': 'lifeshare',
        'serviceProviderName': 'Lifeshare',
        'serviceProviderSynopsis': 'Assistance and support for people facing homelessness, exploitation and poverty.',
        'keywords': [
          'Training',
          'Mentoring'
        ],
        'longitude': -2.2316221630479,
        'latitude': 53.4835909837923,
        'customMessage': null
      },
      {
        'id': '58c689621b4f880c10b65295',
        'description': 'Men&#39;s clothes',
        'type': 'items',
        'reason': 'Lifeshare need to restock on men&#39;s jeans, coats, tracksuits, trainers and underwear. Please visit their office or contact them directly if you have items to offer.',
        'moreInfoUrl': null,
        'postcode': 'M1 1EB',
        'instructions': '',
        'email': 'office@lifeshare.org.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-03-13T11:58:26.4930000Z',
        'neededDate': '2017-03-13T11:58:26.4930000Z',
        'serviceProviderId': 'lifeshare',
        'serviceProviderName': 'Lifeshare',
        'serviceProviderSynopsis': 'Assistance and support for people facing homelessness, exploitation and poverty.',
        'keywords': [
          'Jeans',
          'coats',
          'tracksuits',
          'trainers',
          'underwear'
        ],
        'longitude': -2.2316221630479,
        'latitude': 53.4835909837923,
        'customMessage': null
      },
      {
        'id': '56d9ba46a3b948fda0b49374',
        'description': 'Interview &amp; job seeking skills',
        'type': 'time',
        'reason': 'We support young people to get into employment so they can support themselves and live independent lives. Help with getting a job would be invaluable.',
        'moreInfoUrl': 'http: //www.lifeshare.org.uk/volunteer/breakfast',
        'postcode': 'M1 1EB',
        'instructions': 'No specific skills or qualifications required. Please contact us for more detail.',
        'email': 'viv@streetsupport.net',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-03-04T16:39:34.2750000Z',
        'neededDate': '2016-03-04T16:39:34.2750000Z',
        'serviceProviderId': 'lifeshare',
        'serviceProviderName': 'Lifeshare',
        'serviceProviderSynopsis': 'Assistance and support for people facing homelessness, exploitation and poverty.',
        'keywords': [
          'Employability'
        ],
        'longitude': -2.2316221630479,
        'latitude': 53.4835909837923,
        'customMessage': null
      },
      {
        'id': '58ce4e63b421f81088bb30f0',
        'description': 'Two laptops',
        'type': 'items',
        'reason': 'We need 2 laptops to assist our work with people facing homelessness - can you help? No problem with second hand as long as they work. Or are you a Manchester business that could help us with a gift in kind?',
        'moreInfoUrl': null,
        'postcode': 'M1 1EB',
        'instructions': '',
        'email': 'yvonne@barnabusmanchester.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-03-19T09:24:51.2090000Z',
        'neededDate': '2017-03-19T09:24:51.2090000Z',
        'serviceProviderId': 'lifeshare',
        'serviceProviderName': 'Lifeshare',
        'serviceProviderSynopsis': 'Assistance and support for people facing homelessness, exploitation and poverty.',
        'keywords': [
          'Laptop'
        ],
        'longitude': -2.2316221630479,
        'latitude': 53.4835909837923,
        'customMessage': null
      },
      {
        'id': '56d9bab5a3b948fda0b49375',
        'description': 'Maintenance repair &amp; cleaning',
        'type': 'time',
        'reason': 'Our building needs work and volunteers to help us enables our core staff to focus on our client&#39;s needs.',
        'moreInfoUrl': 'http: //www.lifeshare.org.uk/volunteer/breakfast',
        'postcode': 'M1 1EB',
        'instructions': 'Please get in touch to find out more during our core opening hours.',
        'email': 'viv@streetsupport.net',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-03-04T16:41:25.8820000Z',
        'neededDate': '2016-03-04T16:41:25.8820000Z',
        'serviceProviderId': 'lifeshare',
        'serviceProviderName': 'Lifeshare',
        'serviceProviderSynopsis': 'Assistance and support for people facing homelessness, exploitation and poverty.',
        'keywords': [
          'Builder',
          'DIY'
        ],
        'longitude': -2.2316221630479,
        'latitude': 53.4835909837923,
        'customMessage': null
      },
      {
        'id': '58e7fac1faad651940cd72ec',
        'description': 'Sunday Volunteers ',
        'type': 'time',
        'reason': 'We have a couple of vacancies for our Sunday service... This role is open to all applications via https: //goo.gl/forms/0GL6bIMxXRc54Gcj1&#10;&#10;The process requires;&#10;Application form&#10;Reference checks&#10;Induction inc building induction &#10;&#10;We look forward to your application ',
        'moreInfoUrl': 'https: //goo.gl/forms/0GL6bIMxXRc54Gcj1',
        'postcode': 'M4 1LE',
        'instructions': '',
        'email': 'volunteer@coffee4craig.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-04-07T20:46:57.0940000Z',
        'neededDate': '2017-04-07T20:46:57.0940000Z',
        'serviceProviderId': 'coffee4craig',
        'serviceProviderName': 'Coffee4Craig ',
        'serviceProviderSynopsis': 'Holistic homelessness support. ',
        'keywords': [
          'Volunteer'
        ],
        'longitude': -2.23401712221756,
        'latitude': 53.483397559647,
        'customMessage': null
      },
      {
        'id': '5876aff7b2c3d60fc0ed730f',
        'description': 'Sleeping bags',
        'type': 'items',
        'reason': 'YPSF need a stock of 10-12 sleeping bags which they can use when extra accommodation is provided during cold weather periods.',
        'moreInfoUrl': null,
        'postcode': 'M4 1LE',
        'instructions': '',
        'email': 'A.Sporidou@ypsf.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-01-11T22:21:43.5230000Z',
        'neededDate': '2017-01-11T22:21:43.5230000Z',
        'serviceProviderId': 'ypsf',
        'serviceProviderName': 'Centrepoint - Manchester',
        'serviceProviderSynopsis': 'Centrepoint Manchester is the main access point for young people aged 16 to 25 who are homeless or at risk of homelessness.',
        'keywords': [
          'Sleeping bags'
        ],
        'longitude': -2.23401712221756,
        'latitude': 53.483397559647,
        'customMessage': 'Sleeping bags needed for @y_p_s_f to use for cold weather provision.'
      },
      {
        'id': '5878f000b2c3d6186c0d7bf8',
        'description': 'Mobile creche',
        'type': 'time',
        'reason': 'YPSF runs tenancy training for young people facing homelessness to help them cope once they move into their own accommodation. Often young mums can&#39;t attend because they don&#39;t have childcare available. We would like to talk to anyone that could connect with us to provide a mobile creche, or offer free childcare places in a local scheme. Please contact us for more information.',
        'moreInfoUrl': null,
        'postcode': 'M4 1LE',
        'instructions': '',
        'email': 'M.Pollitt@ypsf.co.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2017-01-13T15:19:28.9900000Z',
        'neededDate': '2017-01-13T15:19:28.9900000Z',
        'serviceProviderId': 'ypsf',
        'serviceProviderName': 'Centrepoint - Manchester',
        'serviceProviderSynopsis': 'Centrepoint Manchester is the main access point for young people aged 16 to 25 who are homeless or at risk of homelessness.',
        'keywords': [
          'Creche',
          'Childcare'
        ],
        'longitude': -2.23401712221756,
        'latitude': 53.483397559647,
        'customMessage': 'Mobile creche needed for mothers attending training for @y_p_s_f'
      },
      {
        'id': '57ebe9f0cbad0f3754c3246e',
        'description': 'Adult socks',
        'type': 'items',
        'reason': 'We need new pairs of adult socks to use for homeless patients as part of the prevention of trench foot and other diseases experienced by people sleeping rough over the winter period.',
        'moreInfoUrl': null,
        'postcode': 'M4 6EE',
        'instructions': 'Donations can be left at reception at Urban Village Medical Practice, handed in to Elliott&#39;s greengrocer in The Chorlton precinct, or contact Rachel for collection on  0161 2725652.',
        'email': 'rachelbrennan@nhs.net',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-09-28T16:04:00.4370000Z',
        'neededDate': '2016-09-28T16:04:00.4370000Z',
        'serviceProviderId': 'urban-village-medical-practice',
        'serviceProviderName': 'Urban Village Medical Practice',
        'serviceProviderSynopsis': 'Urban Village Medical Practice is the main provider of primary health care to people facing homelessness in Manchester.',
        'keywords': [
          'Socks'
        ],
        'longitude': -2.2194727271716,
        'latitude': 53.4829038305992,
        'customMessage': null
      }
    ],
    'total': 26
  },
  'page2': {
    'links': {
      'next': null,
      'prev': '/v2/service-provider-needs?latitude=53.4873656112133&longitude=-2.22721197039864&index=0&pageSize=21',
      'self': '/v2/service-provider-needs?latitude=53.4873656112133&longitude=-2.22721197039864&index=21&pageSize=21'
    },
    'items': [
      {
        'id': '57f363accbad0f3754c3626b',
        'description': 'Shelving',
        'type': 'items',
        'reason': 'Freestanding shelving needed for one of our night shelter venues to help keep bedding and donated clothing clean and dry when not in use. ',
        'moreInfoUrl': null,
        'postcode': 'M40 7AQ',
        'instructions': '',
        'email': 'nightshelter@greatertogethermanchester.org',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-10-04T00:00:00.9820000Z',
        'neededDate': '2016-10-04T00:00:00.9820000Z',
        'serviceProviderId': 'greater-together-manchester',
        'serviceProviderName': 'Greater Together Manchester',
        'serviceProviderSynopsis': 'Greater Together Manchester coordinates the Greater Manchester Winter Night Shelter.',
        'keywords': [
          'Shelving',
          'Storage'
        ],
        'longitude': -2.21807396831887,
        'latitude': 53.492227407038,
        'customMessage': null
      },
      {
        'id': '581b5c18ea21fb1b7c7453d8',
        'description': 'Kitchen Volunteers',
        'type': 'time',
        'reason': 'We need volunteers to help in our kitchen of our cafe, which is open on a Tuesday, Wednesday and a Thursday. Full training given.',
        'moreInfoUrl': 'http://www.gmcc.support',
        'postcode': 'M1 1JQ',
        'instructions': 'Call 0161 236 2462 for more information',
        'email': 'gmcc.vol@gmail.com',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-11-03T00:00:00.1440000Z',
        'neededDate': '2016-11-03T00:00:00.1440000Z',
        'serviceProviderId': 'gm-community-chaplaincy',
        'serviceProviderName': 'Greater Manchester Community Chaplaincy',
        'serviceProviderSynopsis': 'Help for ex-prisoners',
        'keywords': [
          'Volunteers'
        ],
        'longitude': -2.23605822866979,
        'latitude': 53.4819014613034,
        'customMessage': null
      },
      {
        'id': '581b764bea21fb1b7c74540d',
        'description': 'Volunteer Cleaner',
        'type': 'time',
        'reason': 'We need a volunteer cleaner to help in kitchen of our cafe one afternoon a week on either a Tuesday, Wednesday or a Thursday.',
        'moreInfoUrl': 'http://www.gmcc.support',
        'postcode': 'M1 1JQ',
        'instructions': 'Please call 0161 236 2462 for more information.',
        'email': 'gmcc.vol@gmail.com',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-11-03T00:00:00.2090000Z',
        'neededDate': '2016-11-03T00:00:00.2090000Z',
        'serviceProviderId': 'gm-community-chaplaincy',
        'serviceProviderName': 'Greater Manchester Community Chaplaincy',
        'serviceProviderSynopsis': 'Help for ex-prisoners',
        'keywords': [
          'Volunteer'
        ],
        'longitude': -2.23605822866979,
        'latitude': 53.4819014613034,
        'customMessage': null
      },
      {
        'id': '58062adecbad0f199c89e1ce',
        'description': 'Volunteers Needed for Circles Project',
        'type': 'time',
        'reason': 'Circles of Support and Accountability are support groups formed by volunteers from the community who work with convicted sex offenders to help change their lives and give them the support they need to stop them committing further crimes. In Greater Manchester, Circles of Support and Accountability change lives, stops abuse and protects victims.&#10;&#10;',
        'moreInfoUrl': null,
        'postcode': 'M1 1JQ',
        'instructions': 'Volunteers are vital to the success of Circles of Support and Accountability. Without&#10;them, there would be no Circles programme.&#10;&#10;Our volunteers undertake rigorous screening and training to ensure that the work is right for them. We know that sexual abuse provokes powerful responses within&#10;communities. But our volunteers are chosen for their ability and desire to see offenders successfully rehabilitate and reintegrate into their communities.&#10;&#10;Volunteers in a Circle are given a brief outline of the offender&rsquo;s behaviour and risk factors prior to meeting with them. At the first meeting with the offender, each member of the Circle (including the offender) is asked to commit to a Circles Agreement.&#10;&#10;Volunteers help offenders to keep to their relapse prevention plan, by offering practical and emotional support. The Circle will meet once a week, and later in the life of the Circle, the contact will usually reduce and pairs of volunteers may meet with the offender instead of the whole Circle.&#10;&#10;For more information, please contact Chris Kania on 0161 856 3636.',
        'email': 'Chris.Kania@probation.gsi.gov.uk',
        'donationAmountInPounds': 0,
        'donationUrl': null,
        'creationDate': '2016-10-18T00:00:00.6450000Z',
        'neededDate': '2016-10-18T00:00:00.6450000Z',
        'serviceProviderId': 'gm-community-chaplaincy',
        'serviceProviderName': 'Greater Manchester Community Chaplaincy',
        'serviceProviderSynopsis': 'Help for ex-prisoners',
        'keywords': [
          'Volunteers'
        ],
        'longitude': -2.23605822866979,
        'latitude': 53.4819014613034,
        'customMessage': null
      }
    ],
    'total': 72
  }
}
